{
 "title": "Live Stats",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Trajectory",
   "type": "grafana-xyzchart-panel",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  latitude,\n  longitude,\n  altitude\nFROM cansat_data\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Trajectory",
   "type": "pr0ps-trackmap-panel",
   "gridPos": { "h": 10, "w": 5, "x": 5, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  latitude\nFROM cansat_data\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  longitude\nFROM cansat_data\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Altitude",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  altitude\nFROM cansat_data\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Vertical Speed",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  vertical_speed\nFROM cansat_data\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Net Velocity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  net_velocity\nFROM cansat_data\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Acceleration",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  acceleration\nFROM cansat_data\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "External Temperature",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  external_temperature\nFROM cansat_data\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Internal Temperature",
   "type": "stat",
   "description": "There are two internal temperatures to have a more complete insight into the distribution of heat inside the cansat.",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  internal_temperature_1\nFROM cansat_data\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "UVA Radiation",
   "type": "stat",
   "description": "Add decription",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  uva_1,\n  uva_2\nFROM cansat_data\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  { "title": "Live Video", "type": "innius-video-panel", "gridPos": { "h": 13, "w": 10, "x": 0, "y": 10 } },
  {
   "title": "Beta Particles Detected",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 14, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "part" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  beta_particles\nFROM cansat_data\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "IAQ",
   "type": "stat",
   "description": "Write description",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  iaq\nFROM cansat_data\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  pressure\nFROM cansat_data\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "congm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  co2\nFROM cansat_data\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "bvoc",
   "type": "stat",
   "description": "Add description",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  bvoc\nFROM cansat_data\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  humidity\nFROM cansat_data\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Horizontal Speed",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  horizontal_speed\nFROM cansat_data\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  }
 ]
}