{
 "title": "Time Series",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Altitude and Acceleration Time Series",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  altitude,\n  acceleration\nFROM cansat_data\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Temperature Time Series",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  external_temperature,\n  internal_temperature_1,\n  internal_temperature_2\nFROM cansat_data\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Velocity Time Series",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  net_velocity,\n  horizontal_speed,\n  vertical_speed\nFROM cansat_data\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Atmosphere Quality Time Series",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  iaq,\n  pressure,\n  uva_1,\n  uva_2,\n  humidity,\n  bvoc\nFROM cansat_data\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Satellite Connection Time Series",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  satellites_connected\nFROM cansat_data\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  }
 ]
}