apiVersion: 1

datasources:
- name: Cansat
  type: mysql
  url: $DATABASE_HOST:$DATABASE_PORT
  user: $DATABASE_USER
  database: $DATABASE_NAME
  secureJsonData:
    password: $DATABASE_PASS
#  jsonData:
#    maxOpenConns: 0
#    maxIdleConns: 2
#    connMaxLifetime: 14400
  version: 1
  editable: true
