{
 "title": "Live Stats",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "panels": [
  { "title": "Live Video", "type": "innius-video-panel", "gridPos": { "h": 13, "w": 10, "x": 0, "y": 0 } },
  {
   "title": "Altitude",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  altitude\nFROM cansat_data\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "External Temperature",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  external_temperature\nFROM cansat_data\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Internal Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "qagi935",
     "rawSql": "SELECT internal_temperature FROM qagi935.cansat_stats LIMIT 50 "
    }
   ]
  },
  {
   "title": "Velocity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "qagi935",
     "rawSql": "SELECT speed FROM qagi935.cansat_stats LIMIT 50 "
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  pressure\nFROM cansat_data\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  humidity\nFROM cansat_data\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Trajectory",
   "type": "pr0ps-trackmap-panel",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  latitude\nFROM cansat_data\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  longitude\nFROM cansat_data\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Air composition",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  iaq\nFROM cansat_data\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Acceleration",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "accMS2" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "qagi935",
     "rawSql": "SELECT acceleration FROM qagi935.cansat_stats LIMIT 50 "
    }
   ]
  },
  {
   "title": "Beta Particles Detected",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "part" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "qagi935",
     "rawSql": "SELECT beta_particles FROM qagi935.cansat_stats LIMIT 50 "
    }
   ]
  }
 ]
}